/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Mahjong Score API (Dev)
 * OpenAPI spec version: 1.0.0
 */
/**
 * Errors
 */
export type ErrorErrors = {[key: string]: unknown};

export interface Error {
  /** Error code */
  code?: number;
  /** Error name */
  status?: string;
  /** Error message */
  message?: string;
  /** Errors */
  errors?: ErrorErrors;
}

export interface PaginationMetadata {
  total?: number;
  total_pages?: number;
  first_page?: number;
  last_page?: number;
  page?: number;
  previous_page?: number;
  next_page?: number;
}

export interface ValidationErrorField { [key: string]: unknown }

export type ErrorResponseErrors = {[key: string]: ValidationErrorField};

export interface ErrorResponse {
  code: number;
  status: string;
  errors: ErrorResponseErrors;
}

export interface ShareLink {
  /** 共有アクセス用キー */
  short_key: string;
  /** アクセスレベル（VIEW/EDIT/OWNER） */
  access_level: string;
  /** 作成者 */
  readonly created_by?: string;
  /** 作成日時 */
  readonly created_at?: string;
}

export interface GroupLink {
  /** 閲覧用キー */
  readonly view_link?: string;
  /** 編集用キー */
  readonly edit_link?: string;
  /** 管理者用キー */
  readonly owner_link?: string;
  /** グループに紐づく共有リンク一覧 */
  readonly group_links?: readonly ShareLink[];
}

export interface Tournament {
  /** 閲覧用キー */
  readonly view_link?: string;
  /** 編集用キー */
  readonly edit_link?: string;
  /** 管理者用キー */
  readonly owner_link?: string;
  /** 大会ID */
  readonly id: number;
  /** グループID */
  readonly group_id: number;
  /** 大会名 */
  name: string;
  /**
   * 大会説明
   * @nullable
   */
  description?: string | null;
  /** レート */
  rate: number;
  /** 作成時のKey */
  readonly created_by?: string;
  /** 大会作成日時（ISO 8601形式） */
  readonly created_at?: string;
  /**
   * 大会開始日時（ISO 8601形式）
   * @nullable
   */
  started_at?: string | null;
  /** 大会が所属するグループ情報 */
  readonly parent_group_link: GroupLink;
  /** 大会に紐づく共有リンク一覧 */
  readonly tournament_links: readonly ShareLink[];
}

export interface TournamentUpdate {
  /** 大会名 */
  name?: string;
  /**
   * 大会説明
   * @nullable
   */
  description?: string | null;
  /** レート */
  rate?: number;
  /**
   * 大会開始日時（ISO 8601形式）
   * @nullable
   */
  started_at?: string | null;
}

export interface Message {
  message?: string;
}

export interface TournamentLink {
  /** 閲覧用キー */
  readonly view_link?: string;
  /** 編集用キー */
  readonly edit_link?: string;
  /** 管理者用キー */
  readonly owner_link?: string;
  /** 親トーナメントに紐づく共有リンク一覧 */
  readonly tournament_links?: readonly ShareLink[];
}

/**
 * 卓タイプ
 */
export type TableType = typeof TableType[keyof typeof TableType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableType = {
  NORMAL: 'NORMAL',
  CHIP: 'CHIP',
} as const;

export interface Table {
  /** 閲覧用キー */
  readonly view_link?: string;
  /** 編集用キー */
  readonly edit_link?: string;
  /** 管理者用キー */
  readonly owner_link?: string;
  /** 卓ID */
  readonly id: number;
  /** 大会ID */
  readonly tournament_id: number;
  /** 卓名 */
  name: string;
  /** 卓タイプ */
  type: TableType;
  /** 作成時のKey */
  readonly created_by?: string;
  /** 卓作成日時（ISO 8601形式） */
  readonly created_at?: string;
  /** 卓が所属する大会の情報 */
  readonly parent_tournament_link: TournamentLink;
  /** 卓に紐づく共有リンク一覧 */
  readonly table_links?: readonly ShareLink[];
}

/**
 * 卓タイプ
 */
export type TableCreateType = typeof TableCreateType[keyof typeof TableCreateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableCreateType = {
  NORMAL: 'NORMAL',
  CHIP: 'CHIP',
} as const;

export interface TableCreate {
  /** 卓名 */
  name: string;
  /** 卓タイプ */
  type?: TableCreateType;
}

export interface GroupCreate {
  /** 作成用トークン */
  token: string;
}

export interface Group {
  /** 閲覧用キー */
  readonly view_link?: string;
  /** 編集用キー */
  readonly edit_link?: string;
  /** 管理者用キー */
  readonly owner_link?: string;
  readonly id?: number;
  name: string;
  /** @nullable */
  description?: string | null;
  readonly created_by?: string;
  readonly created_at?: string;
  readonly last_updated_at?: string;
  /** グループに紐づく共有リンク一覧 */
  readonly group_links?: readonly ShareLink[];
}

export interface GroupRequest {
  /** グループ名 */
  name: string;
  /** メールアドレス一覧 */
  email: string;
  /** ユーザーのタイムゾーン（例: 'Asia/Tokyo'） */
  timezone?: string;
}

export interface GroupResponse {
  /** メッセージ */
  message: string;
  /** 有効期限 */
  expires_at: string;
}

export interface GroupUpdate {
  /** グループ名 */
  name?: string;
  /**
   * 説明
   * @nullable
   */
  description?: string | null;
}

export interface TournamentCreate {
  /** 大会名 */
  name: string;
  /**
   * 大会説明
   * @nullable
   */
  description?: string | null;
  /**
   * レート
   * @nullable
   */
  rate?: number | null;
}

export interface Player {
  readonly id: number;
  group_id: number;
  name: string;
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  display_order?: number | null;
}

export interface PlayerCreate {
  /** プレイヤー名 */
  name: string;
  /**
   * ニックネーム
   * @nullable
   */
  nickname?: string | null;
  /**
   * 表示順
   * @nullable
   */
  display_order?: number | null;
}

export interface PlayerUpdate {
  name?: string;
  /** @nullable */
  nickname?: string | null;
  display_order?: number;
}

/**
 * 卓タイプ
 */
export type TableUpdateType = typeof TableUpdateType[keyof typeof TableUpdateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableUpdateType = {
  NORMAL: 'NORMAL',
  CHIP: 'CHIP',
} as const;

export interface TableUpdate {
  /** 卓名 */
  name?: string;
  /** 卓タイプ */
  type?: TableUpdateType;
}

export interface ScoreInput {
  /** プレイヤーID */
  player_id: number;
  /** 得点（合計0である必要あり） */
  score: number;
}

export interface Game {
  /** 閲覧用キー */
  readonly view_link?: string;
  /** 編集用キー */
  readonly edit_link?: string;
  /** 管理者用キー */
  readonly owner_link?: string;
  readonly id?: number;
  table_id: number;
  game_index: number;
  /** @nullable */
  memo?: string | null;
  /** @nullable */
  played_at?: string | null;
  readonly created_by?: string;
  readonly created_at?: string;
  scores?: ScoreInput[];
  /** 対局に紐づく共有リンク一覧 */
  readonly game_links?: readonly ShareLink[];
}

export interface GameCreate {
  /** スコア一覧 */
  scores: ScoreInput[];
  /**
   * メモ
   * @nullable
   */
  memo?: string | null;
}

export interface GameUpdate {
  /** 対局インデックス */
  game_index?: number;
  /**
   * メモ
   * @nullable
   */
  memo?: string | null;
  /**
   * 対局日時
   * @nullable
   */
  played_at?: string | null;
  /** スコア一覧 */
  scores?: ScoreInput[];
}

export type TournamentParticipantsErrorsItem = {[key: string]: unknown};

export interface TournamentParticipants {
  tournament_id: number;
  /** 大会に登録されているプレイヤー一覧 */
  participants: Player[];
  /** 登録時のエラー情報一覧 */
  errors?: TournamentParticipantsErrorsItem[];
  /** 追加された参加者の数 */
  added_count?: number;
}

export interface TournamentParticipant {
  /** 大会に登録するプレイヤーID */
  player_id: number;
  readonly created_at?: string;
}

export interface TournamentParticipantsCreate {
  /** 大会に登録するプレイヤー一覧 */
  participants: TournamentParticipant[];
}

export interface TablePlayers {
  table_key: string;
  /** 卓に参加するプレイヤー一覧 */
  readonly table_players: readonly Player[];
  /** 登録時のエラー情報一覧 */
  errors?: string[];
}

export interface TablePlayerItem {
  /** 参加するプレイヤーID */
  player_id: number;
  /**
   * 卓での座席位置
   * @nullable
   */
  seat_position?: number | null;
}

export interface TablePlayerCreate {
  /**
   * 卓に参加するプレイヤー一覧（player_id, seat_position のリスト）
   * @minItems 1
   */
  players: TablePlayerItem[];
}

export interface PlayerScore {
  /** プレイヤーID */
  id: number;
  /** プレイヤー名 */
  name: string;
  /** 参加ゲーム数 */
  games_played?: number;
  /** 合計スコア */
  total_score?: number;
}

/**
 * 大会情報
 */
export type TournamentExportTournament = {[key: string]: unknown};

export interface TournamentExport {
  /** 大会情報 */
  tournament: TournamentExportTournament;
  /** 大会に参加する全プレイヤーとそのスコア情報 */
  players?: PlayerScore[];
}

/**
 * グループ情報
 */
export type GroupSummaryGroup = {[key: string]: unknown};

export interface GroupSummary {
  /** グループ情報 */
  group: GroupSummaryGroup;
  /** グループに含まれる大会一覧 */
  tournaments?: TournamentExport[];
}

/**
 * テーブル（卓）のタイプ
 */
export type TableInfoType = typeof TableInfoType[keyof typeof TableInfoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableInfoType = {
  NORMAL: 'NORMAL',
  CHIP: 'CHIP',
} as const;

export interface TableInfo {
  /** テーブル（卓）のID */
  id: number;
  /** テーブル（卓）の名前 */
  name: string;
  /** テーブル（卓）のタイプ */
  type: TableInfoType;
}

/**
 * 各テーブルごとのスコア辞書。例: {'1': 25000, '2': -5000}
 */
export type PlayerScoreMapScores = {[key: string]: number};

export interface PlayerScoreMap {
  /** プレイヤーID */
  id: number;
  /** プレイヤー名 */
  name: string;
  /** 各テーブルごとのスコア辞書。例: {'1': 25000, '2': -5000} */
  scores?: PlayerScoreMapScores;
  /** 合計スコア（全テーブルの合計） */
  total?: number;
  /** 換算スコア（合計スコア × レート） */
  converted_total?: number;
}

export interface TournamentScoreMap {
  /** 大会ID */
  tournament_id: number;
  /** 大会に含まれる卓（テーブル）の一覧 */
  tables: TableInfo[];
  /** 大会に参加する全プレイヤーとそのスコア情報 */
  players: PlayerScoreMap[];
  /** 換算レート */
  rate?: number;
}

/**
 * Default error response
 */
export type DefaultErrorResponse = Error;

/**
 * Unprocessable Entity
 */
export type UnprocessableEntityResponse = Error;

