"""Add group name to GroupCreationToken

Revision ID: 0919d167f30f
Revises: 23eef0b7a5b0
Create Date: 2025-10-30 04:28:54.355201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0919d167f30f'
down_revision = '23eef0b7a5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_group_creation_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_group_creation_tokens', schema=None) as batch_op:
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
