"""add group invitation table

Revision ID: 23eef0b7a5b0
Revises: 57d581d7ff39
Create Date: 2025-10-29 21:05:38.998549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23eef0b7a5b0'
down_revision = '57d581d7ff39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_group_creation_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_group_creation_tokens')
    # ### end Alembic commands ###
