"""Add AccessLevel Enum and last_updated_at to Group

Revision ID: 2e7203e9bfee
Revises: 015f9777aef6
Create Date: 2025-10-04 20:05:57.922973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e7203e9bfee'
down_revision = '015f9777aef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_key', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Enum('VIEW', 'EDIT', 'OWNER', name='accesslevel'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_key')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_index(batch_op.f('edit_key'))
        batch_op.drop_index(batch_op.f('group_key'))
        batch_op.drop_column('group_key')
        batch_op.drop_column('edit_key')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('edit_key'))
        batch_op.drop_index(batch_op.f('table_key'))
        batch_op.drop_column('table_key')
        batch_op.drop_column('edit_key')

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('edit_key'))
        batch_op.drop_index(batch_op.f('tournament_key'))
        batch_op.drop_column('edit_key')
        batch_op.drop_column('tournament_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_key', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('edit_key', mysql.VARCHAR(length=64), nullable=False))
        batch_op.create_index(batch_op.f('tournament_key'), ['tournament_key'], unique=True)
        batch_op.create_index(batch_op.f('edit_key'), ['edit_key'], unique=True)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_key', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('table_key', mysql.VARCHAR(length=64), nullable=False))
        batch_op.create_index(batch_op.f('table_key'), ['table_key'], unique=True)
        batch_op.create_index(batch_op.f('edit_key'), ['edit_key'], unique=True)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_key', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('group_key', mysql.VARCHAR(length=64), nullable=False))
        batch_op.create_index(batch_op.f('group_key'), ['group_key'], unique=True)
        batch_op.create_index(batch_op.f('edit_key'), ['edit_key'], unique=True)
        batch_op.drop_column('last_updated_at')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')

    op.drop_table('share_links')
    # ### end Alembic commands ###
