"""change table.type to enum

Revision ID: 57d581d7ff39
Revises: a7bc02c74524
Create Date: 2025-10-26 20:30:01.992574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57d581d7ff39'
down_revision = 'a7bc02c74524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tables', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('NORMAL', 'CHIP', name='tabletypeenum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tables', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('NORMAL', 'CHIP', name='tabletypeenum'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
