"""Add contact table

Revision ID: 6003da5c7632
Revises: 84926889b30b
Create Date: 2025-11-25 10:10:11.735229

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6003da5c7632"
down_revision = "84926889b30b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tbl_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED", "IN_PROGRESS", "ANSWERED", "CLOSED", name="contactstatus"
            ),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tbl_contacts")
    # ### end Alembic commands ###
