"""Add group_id to group_creation_tokens

Revision ID: 75da5967ea0c
Revises: 9d8a65c64392
Create Date: 2026-08-01 00:15:06.172041

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "75da5967ea0c"
down_revision = "9d8a65c64392"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tbl_group_creation_tokens", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None, "tbl_groups", ["group_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tbl_group_creation_tokens", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###
