"""add email to groups

Revision ID: 84926889b30b
Revises: 0919d167f30f
Create Date: 2025-10-31 00:08:57.948597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84926889b30b'
down_revision = '0919d167f30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_tbl_groups_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_groups_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
