"""add ip_address to group creation tokens

Revision ID: 9d8a65c64392
Revises: 6003da5c7632
Create Date: 2026-06-09 12:26:29.088897

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d8a65c64392"
down_revision = "6003da5c7632"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tbl_group_creation_tokens", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ip_address", sa.String(length=45), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tbl_group_creation_tokens", schema=None) as batch_op:
        batch_op.drop_column("ip_address")

    # ### end Alembic commands ###
