"""Initial create with tbl_ prefix

Revision ID: afe88385021b
Revises: 
Create Date: 2025-10-16 05:33:07.667931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe88385021b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_key', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Enum('VIEW', 'EDIT', 'OWNER', name='accesslevel'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_key')
    )
    op.create_table('tbl_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['tbl_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['tbl_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tbl_tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_tournament_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['tbl_players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tbl_tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tbl_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_table_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('seat_position', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['tbl_players.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tbl_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('uma', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['tbl_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['tbl_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_scores')
    op.drop_table('tbl_table_players')
    op.drop_table('tbl_games')
    op.drop_table('tbl_tournament_players')
    op.drop_table('tbl_tables')
    op.drop_table('tbl_tournaments')
    op.drop_table('tbl_players')
    op.drop_table('tbl_share_links')
    op.drop_table('tbl_groups')
    # ### end Alembic commands ###
